name: 📝 Registrar Nuevo Dispositivo
description: Agrega un nuevo equipo al inventario físico
title: "Registro: [Modelo]"
labels: ["nuevo-registro"]
body:
  - type: input
    id: id_num
    attributes:
      label: ID Numérico
      description: El número que irá en la URL y en la etiqueta/QR del equipo.
      placeholder: ej. 105
    validations:
      required: true
  - type: input
    id: modelo
    attributes:
      label: Modelo del Dispositivo
      placeholder: ej. Nodo Sensor Humedal
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Versión de Hardware
      placeholder: ej. v1.0
    validations:
      required: true
  - type: dropdown
    id: estado
    attributes:
      label: Estado Actual
      options:
        - "🟢 En Stock"
        - "🔵 En Terreno"
        - "🟡 En Mantenimiento"
        - "🔴 Dado de Baja"
    validations:
      required: true
